# DBView configuration file

customer = 15993

## on windows path, use the '/', eg:
# pgsql-bin = "C:/Program Files/PostgreSQL/9.3/bin"


[local-database]
ssl = "disable"
username = "postgres"
password = "postgres"
host = "127.0.0.1"
database = "postgres"
port = 5432
target_username = "dbview"
target_database = "umovme_dbview_db"



## You can get the user and password with our support team.
[remote-database]
ssl = "disable"
# username = ""
# password = ""
host = "dbview.umov.me"
database = "prod_umov_dbview"
port = 9999